#!/usr/bin/env python3
"""Build the three main report maps and the Appendix FAO ASIS map.

Non-map graphics are generated by Stata. This script is intentionally limited
to maps and reads all indicators from existing derived tables or the Appendix
corridor crosswalk.
"""

from __future__ import annotations

from pathlib import Path

import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.colors import ListedColormap
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
from shapely import make_valid


PROJECT = Path(__file__).resolve().parents[1]
WORKSPACE = next(parent for parent in PROJECT.parents if parent.name == "01_workspace")
GUATEMALA = WORKSPACE / "02_projects" / "07_Playdata" / "02_Guatemala"
MUNIS = GUATEMALA / "sources" / "JSON_Departamenos_Municipios_LugaresPoblados" / "Mapas-TopoJSON-Guatemala-main" / "munis.json"
DERIVED = PROJECT / "derived"
FIGURES = PROJECT / "figures"
APP_FIGURES = PROJECT / "figures" / "Appendix"
APP_TABLES = PROJECT / "figures" / "Appendix" / "tables"

SITES = [("Olopa", "Chiquimula"), ("Chahal", "Alta Verapaz"), ("Patzité", "Quiché")]
PERCENTILE_LABELS = [
    "0: below all 45 past totals\n(record low)",
    "1–10: exceptionally dry",
    "11–25: dry",
    "26–50: below median",
    "51–75: above median",
    "76–100: wet relative to history",
]
PERCENTILE_COLOURS = ["#7f0000", "#d7301f", "#fc8d59", "#fee8c8", "#9ecae1", "#2171b5"]


def load_geometry() -> gpd.GeoDataFrame:
    geo = gpd.read_file(MUNIS)
    if geo.crs is None:
        geo = geo.set_crs("EPSG:4326")
    geo = geo.loc[~geo["id"].astype(str).eq("0") & ~geo["Departamento"].str.upper().eq("BELICE")].copy()
    geo.loc[~geo.geometry.is_valid, "geometry"] = geo.loc[~geo.geometry.is_valid, "geometry"].map(make_valid)
    geo["municipality_id"] = pd.to_numeric(geo["id"], errors="raise").astype(int)
    geo = geo.rename(columns={"Departamento": "department", "Municipio": "municipality"})
    if len(geo) != 340:
        raise ValueError("Expected 340 municipality polygons.")
    return geo[["municipality_id", "department", "municipality", "geometry"]]


def percentile_group(value: float) -> int:
    if value == 0:
        return 0
    if value <= 10:
        return 1
    if value <= 25:
        return 2
    if value <= 50:
        return 3
    if value <= 75:
        return 4
    return 5


def site_points(geo: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
    points = geo.to_crs("EPSG:6933").copy()
    points["geometry"] = points.centroid
    points = points.to_crs("EPSG:4326")
    return points.merge(pd.DataFrame(SITES, columns=["municipality", "department"]), on=["municipality", "department"])


def map_base(ax, geo: gpd.GeoDataFrame, groups: bool) -> None:
    if groups:
        geo.plot(ax=ax, column="percentile_group", cmap=ListedColormap(PERCENTILE_COLOURS), vmin=0, vmax=5,
                 edgecolor="#ffffff", linewidth=0.18, zorder=1)
    else:
        geo.plot(ax=ax, color="#f8fafc", edgecolor="#cbd5e1", linewidth=0.24, zorder=1)
    ax.set_axis_off()
    ax.set_aspect("equal")


def draw_sites(ax, sites: gpd.GeoDataFrame) -> None:
    sites.plot(ax=ax, marker="o", color="#111827", edgecolor="white", linewidth=0.6, markersize=37, zorder=8)
    for item in sites.itertuples():
        ax.annotate(item.municipality, (item.geometry.x, item.geometry.y), xytext=(4, 4), textcoords="offset points",
                    fontsize=7.3, zorder=9, bbox=dict(facecolor="white", edgecolor="none", alpha=0.8, pad=0.18))


def draw_corridor_lines(ax, geo: gpd.GeoDataFrame) -> list:
    legacy = geo.loc[geo["legacy_sesan_core_2016"].eq(1)].geometry.union_all()
    expanded = geo.loc[geo["sesan_expanded_only_2025"].eq(1)].geometry.union_all()
    gpd.GeoSeries([expanded], crs=geo.crs).boundary.plot(ax=ax, color="#2563eb", linewidth=1.05,
                                                          linestyle=(0, (5, 4)), zorder=5)
    gpd.GeoSeries([legacy], crs=geo.crs).boundary.plot(ax=ax, color="#111827", linewidth=1.8, zorder=6)
    return [
        Line2D([0], [0], color="#111827", lw=1.8, label="Legacy SESAN core list (solid; 67 annex matches)"),
        Line2D([0], [0], color="#2563eb", lw=1.05, linestyle=(0, (5, 4)), label="Current SESAN expanded-only (dashed; 93)"),
    ]


def figure_note(fig, text: str) -> None:
    fig.text(0.01, 0.012, text, ha="left", va="bottom", fontsize=7.4, wrap=True)


def map_chirps(geo: gpd.GeoDataFrame, points: gpd.GeoDataFrame) -> None:
    fig, ax = plt.subplots(figsize=(8.5, 8.8))
    map_base(ax, geo, groups=True)
    draw_sites(ax, points)
    ax.set_title("CHIRPS rainfall rarity, Guatemala, May–August 2026", fontsize=13, fontweight="bold")
    handles = [Patch(facecolor=colour, edgecolor="white", label=label) for colour, label in zip(PERCENTILE_COLOURS, PERCENTILE_LABELS, strict=True)]
    handles.append(Line2D([0], [0], marker="o", color="w", markerfacecolor="#111827", markersize=6, label="Field municipality"))
    ax.legend(handles=handles, loc="lower left", fontsize=7.1, frameon=True, framealpha=0.96)
    figure_note(fig, "Data: CHIRPS v3 FINAL pentads, municipality area-weighted cumulative rainfall, 1 May–31 August 2026; reference distribution: 1981–2025. "
                     "Unit: empirical historical percentile. A value of 0 means 2026 was below every one of the 45 previous municipality totals; it is deliberately separate from the 1–10 category. "
                     "This is a meteorological rainfall measure, not crop loss.")
    fig.tight_layout(rect=(0, 0.10, 1, 1))
    fig.savefig(FIGURES / "fig01a_chirps_record_percentile.png", dpi=250, bbox_inches="tight")
    plt.close(fig)


def map_corridor(geo: gpd.GeoDataFrame, points: gpd.GeoDataFrame) -> None:
    fig, ax = plt.subplots(figsize=(8.5, 8.8))
    map_base(ax, geo, groups=False)
    handles = draw_corridor_lines(ax, geo)
    draw_sites(ax, points)
    handles.append(Line2D([0], [0], marker="o", color="w", markerfacecolor="#111827", markersize=6, label="Field municipality"))
    ax.legend(handles=handles, loc="lower left", fontsize=7.2, frameon=True, framealpha=0.96)
    ax.set_title("SESAN corridor definitions used in this report", fontsize=13, fontweight="bold")
    figure_note(fig, "Data: existing current SESAN 160-municipality Corredor Seco Ampliado indicator; legacy SESAN 2016 annex list matched to the same 340 municipality polygons. "
                     "Administrative prioritisation lists, not a measured 2026 drought surface. Solid line = legacy/core list; dashed line = municipalities in the current expanded list but outside the legacy list. "
                     "The 2016 text says 66 municipalities, while its enumerated annex matches 67 polygons; see Appendix documentation.")
    fig.tight_layout(rect=(0, 0.10, 1, 1))
    fig.savefig(FIGURES / "fig01b_sesan_corridor_definitions.png", dpi=250, bbox_inches="tight")
    plt.close(fig)


def map_overlap(geo: gpd.GeoDataFrame, points: gpd.GeoDataFrame) -> None:
    fig, ax = plt.subplots(figsize=(8.5, 8.8))
    map_base(ax, geo, groups=True)
    handles = draw_corridor_lines(ax, geo)
    draw_sites(ax, points)
    percentile_handles = [Patch(facecolor=colour, edgecolor="white", label=label) for colour, label in zip(PERCENTILE_COLOURS, PERCENTILE_LABELS, strict=True)]
    handles = percentile_handles + handles + [Line2D([0], [0], marker="o", color="w", markerfacecolor="#111827", markersize=6, label="Field municipality")]
    ax.legend(handles=handles, loc="lower left", fontsize=6.7, frameon=True, framealpha=0.96, ncol=1)
    ax.set_title("CHIRPS rainfall rarity overlaid with SESAN corridor definitions", fontsize=12.5, fontweight="bold")
    figure_note(fig, "Data: CHIRPS v3 FINAL municipality rainfall percentile, 1 May–31 August 2026 versus 1981–2025; current 160-municipality SESAN expanded indicator and legacy SESAN 2016 annex list. "
                     "Fills are meteorological rainfall rarity; solid/dashed outlines are administrative priority lists. Their overlap is descriptive and does not establish a causal relationship or crop loss.")
    fig.tight_layout(rect=(0, 0.12, 1, 1))
    fig.savefig(FIGURES / "fig01c_chirps_sesan_overlap.png", dpi=250, bbox_inches="tight")
    plt.close(fig)


def map_fao(geo: gpd.GeoDataFrame, points: gpd.GeoDataFrame) -> None:
    fig, ax = plt.subplots(figsize=(8.5, 8.8))
    classes = pd.cut(geo["asis_value"], bins=[-0.001, 1, 10, 30, 60, 100.001], labels=False)
    geo = geo.assign(asis_class=classes)
    palette = ["#f7fbff", "#c6dbef", "#6baed6", "#2171b5", "#08306b"]
    geo.plot(ax=ax, column="asis_class", cmap=ListedColormap(palette), vmin=0, vmax=4, edgecolor="#ffffff", linewidth=0.18, zorder=1)
    geo.loc[geo["asis_value"].isna()].plot(ax=ax, facecolor="#e5e7eb", edgecolor="#64748b", hatch="....", linewidth=0.35, zorder=3)
    draw_sites(ax, points)
    ax.set_axis_off(); ax.set_aspect("equal")
    labels = ["0–1%", ">1–10%", ">10–30%", ">30–60%", ">60–100%"]
    handles = [Patch(facecolor=c, edgecolor="white", label=l) for c, l in zip(palette, labels, strict=True)]
    handles += [Patch(facecolor="#e5e7eb", edgecolor="#64748b", hatch="....", label="No valid in-season ASIS cells"),
                Line2D([0], [0], marker="o", color="w", markerfacecolor="#111827", markersize=6, label="Field municipality")]
    ax.legend(handles=handles, loc="lower left", fontsize=7.1, frameon=True, framealpha=0.96)
    ax.set_title("FAO ASIS agricultural vegetation stress, Guatemala", fontsize=13, fontweight="bold")
    figure_note(fig, "Data: supplied FAO ASIS Cropland, Growing Season 1 raster; 2026 August Dekad 1; municipality fractional-pixel, area-weighted statistic. "
                     "Unit: percent of valid in-season cropland area affected by drought-related vegetation stress. ASIS is not percentage crop or yield loss. Municipalities with no valid cells are hatched.")
    fig.tight_layout(rect=(0, 0.10, 1, 1))
    fig.savefig(APP_FIGURES / "app01_fao_asis_municipality_map.png", dpi=250, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    FIGURES.mkdir(parents=True, exist_ok=True)
    APP_FIGURES.mkdir(parents=True, exist_ok=True)
    geo = load_geometry()
    chirps = pd.read_csv(DERIVED / "chirps_2026_municipality.csv")
    asis = pd.read_csv(DERIVED / "fao_asis_2026_municipality.csv")
    corridor = pd.read_csv(APP_TABLES / "table_corridor_definitions.csv")
    geo = geo.merge(chirps[["municipality_id", "rainfall_historical_percentile"]], on="municipality_id", validate="one_to_one")
    geo = geo.merge(asis[["municipality_id", "asis_value"]], on="municipality_id", validate="one_to_one")
    geo = geo.merge(corridor[["municipality_id", "legacy_sesan_core_2016", "sesan_expanded_only_2025"]], on="municipality_id", validate="one_to_one")
    geo["percentile_group"] = geo["rainfall_historical_percentile"].map(percentile_group)
    points = site_points(geo)
    map_chirps(geo, points)
    map_corridor(geo, points)
    map_overlap(geo, points)
    map_fao(geo, points)
    print("Built three main maps and one Appendix FAO map.")


if __name__ == "__main__":
    main()
